### ISSUE TITLE
Custom domain does not mirror the GitHub pages

### ISSUE THREAD

**Issue by gkorpal** [claucece/claucece.github.io#8]
The custom domain https://sofiaceli.com/ does not seem to mirror the GitHub page https://claucece.github.io/ 

For example, one can spot the difference in this screenshot of the Work webpage accessed from both URLs at the same time:
![celi](https://github.com/claucece/claucece.github.io/assets/8099449/fc7ee002-5349-4c2a-8f01-a46fc04a78dd)

I think they were in sync until [this commit](https://github.com/claucece/claucece.github.io/commit/acdaa6664aadc5913fa218c3912271d3d82811ed) from October 20, 2023. However, not in sync since [this commit](https://github.com/claucece/claucece.github.io/commit/9d7a356546728bfaebc5b783e8e18cc7f0dd2171) from October 28, 2023.

**Comment by claucece** [comment]
Hi @gkorpal ! Yes, I don't have them automatically synced, as I do it manually. I won't be making the process automatic as for personal reasons I don't want to ;) Thank you for the issue, though ;)
